# Generated by Django 4.2.3 on 2023-08-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsearch',
            name='search_mode',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Restaurant', 'Restaurant'), ('Places', 'Places')], default='Hotel', max_length=25),
        ),
    ]
