# Generated by Django 4.2.3 on 2023-08-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0002_tripsearch_search_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsearch',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
